version: '3.9'

services:
    postgres:
        image: postgres:latest
        container_name: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: mydb
            POSTGRES_HOST_AUTH_METHOD: trust
        restart: always
        volumes:
            - database-data:/var/lib/postgresql/data/
    backend:
        build: .
        ports:
            - '5000:5000'
        depends_on:
            - postgres
        command: npm run dev
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            DATABASE_URL: postgres://postgres@postgres/mydb
            HOST: 0.0.0.0
            PORT: 5000
            DB_MIN_CONNECTIONS: 3
            DB_MAX_CONNECTIONS: 30
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: quantran2381@gmail.com
            PGADMIN_DEFAULT_PASSWORD: 238200
        ports:
            - '5050:80'
        restart: always
        volumes:
            - pgadmin:/root/.pgadmin
volumes:
    database-data:
    pgadmin:
